name = "kaan-koc-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "PORTFOLIO_DATA"
id = "7155c8481a074fbfb7986d5fe338eb96"
preview_id = "7155c8481a074fbfb7986d5fe338eb96"
