name = "kaan-koc-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "PORTFOLIO_DATA"
id = "portfolio-data-kv"
preview_id = "portfolio-data-kv-preview"
